baseURL = "http://www.ledesertenville.com/"
relativeurls = "true"

theme = "LDEV_theme"
title = "le Désert en Ville — Espace de Création Hors-sol"
[[menu.crea]]
[[menu.main]]
name = "CONTACT"
url = "/about/"
weight = 4
[[menu.main]]
name = "VOYAGEURS"
url = "/voyageurs/"
weight = 3
[[menu.main]]
name = "ATELIERS"
url = "/ateliers/"
weight = 2
[[menu.main]]
name = "CRÉATIONS"
url = "/creations/lettres-vives/"
weight = 1
