baseURL = "http://www.ledesertenville.com/"
theme = "LDEV_theme"
title = "le Désert en Ville — Compagnie d'art vivant"
[[menu.crea]]
[[menu.main]]
name = "HORIZONS"
url = "/horizons/"
weight = 2
[[menu.main]]
name = "CRÉATIONS"
url = "/creations/lettres-vives/index.html"
weight = 1
[[menu.main]]
name = "CONTACT"
url = "/about/"
weight = 4
[[menu.main]]
name = "VOYAGEURS"
url = "/voyageurs/"
weight = 3
