baseURL = ""
title = "le Désert en Ville — Espace de Création Hors-sol"
theme = "LDEV_theme"
canonifyURLs = true


[[menu.main]]
    name = "CRÉATIONS"
    weight = 1
	url = "/creations/lettres-vives/"

[[menu.main]]
    name = "ATELIERS"
    weight = 2
	url = "/ateliers/"

[[menu.main]]
    name = "VOYAGEURS"
    weight = 3
	url = "/voyageurs/"

[[menu.main]]
    name = "CONTACT"
    weight = 4
	url = "/about/"


[[menu.crea]]
