---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/about
  label: About
  create: all
  match: "**/*"
- type: directory
  path: content/creations
  label: Creations
  create: all
  match: "**/*"
- type: directory
  path: content/voyageurs
  label: Voyageurs
  create: all
  match: "**/*"
- type: directory
  path: content/horizons
  label: Horizons
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: ''
  publish_command: ''
  preview_env: []
  publish_env: []
  output_directory: ''
version: '0.26'
