---
pages:
- voyageurs/isabelle-alta.md
- voyageurs/leon-septavaux.md
hide_body: false
fields:
- name: date
  label: Date
  type: datetime
  hidden: false
  default: ''
- name: fonction
  label: Fonction
  type: text
  hidden: false
  default: ''
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: weight
  label: Weight
  type: text
  hidden: false
  default: ''
- name: type
  label: Type
  type: text
  hidden: false
  default: ''
